name: GitHub Actions CI/CD
run-name: ${{ github.actor }} is  Local CI Setup and Deploy onto Vagrant. ðŸš€
on:
  push:
    branches:
      - master
      - level-1
      - level-2
      - level-3
      - level-4
jobs:
  CI:
    runs-on: self-hosted
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ðŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17.0.5
          distribution: adopt
      - name: Build application
        run: |
          make build
      - name: Build Docker image
        run: |
          make docker_build
      - name: Push image student_app
        run: |
          make docker_push
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ðŸ This job's status is ${{ job.status }}."
  CD:
    runs-on: self-hosted
    steps:
#      - name: Deploy to Local
#        run: |
#          make app_run_docker
      - name: Set up SSH key
        env:
          VAGRANT_SSH_KEY: ${{ secrets.VAGRANT_SSH_KEY }}
        run: |
          echo "$VAGRANT_SSH_KEY" | tr -d '\r' > id_rsa
          chmod 0400 id_rsa
          ssh-add id_rsa

      - name: Copy docker-compose file
        run: |
          scp -i id_rsa -P 2222 path/to/docker-compose.yml vagrant@127.0.0.1:/home/vagrant

      - name: Trigger deployment
        run: |
          ssh -i id_rsa -p 2222 vagrant@127.0.0.1 "sudo docker-compose up -d"