name: GitHub Actions CI/CD
run-name: ${{ github.actor }} is testing Local CI Setup and Local CD. ğŸš€
on:
  push :
    branches:
      - master
      - level-1
      - level-2
      - level-3
jobs:
  Build-Student-CRUD:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: openjdk
      - name: Build application
        run: |
          make build
      - name: Build Docker image
        run: |
          make app_run_docker
      - name: Push image
        run: |
          docker push hrithiksawant/student_app:latest
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."